In [18]:
from __future__ import division
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[11,22,33,44],[55,66,77,88]])
c = np.array([[311,322,333,344],[355,366,377,388]])
d = np.array([[1311,1322,1333,1344],[1355,1366,1377,1388]])

In [19]:

a.reshape([4,2])
b.reshape([4,2])
c.reshape([4,2])
d.reshape([4,2])

array([[1311, 1322],
       [1333, 1344],
       [1355, 1366],
       [1377, 1388]])

In [20]:
np.dstack([a,b,c,d])

array([[[   1,   11,  311, 1311],
        [   2,   22,  322, 1322],
        [   3,   33,  333, 1333],
        [   4,   44,  344, 1344]],

       [[   5,   55,  355, 1355],
        [   6,   66,  366, 1366],
        [   7,   77,  377, 1377],
        [   8,   88,  388, 1388]]])

In [27]:
    def encode(classid, cX, cY, boxW, boxH):
        S, B, C, W, H = 3,2,20,448,448
        assert int(classid) <= int(C-1)

        # init skeleton
        class_prob = np.zeros([S*S, C])
        confidence = np.zeros([S*S, B])
        offsetX    = np.zeros([S*S, B])
        offsetY    = np.zeros([S*S, B])
        norsqrtW   = np.zeros([S*S, B])
        norsqrtH   = np.zeros([S*S, B])

        # Some para
        gridX, gridY = int(W/S), int(H/S)
        tarGrid = int(cX/gridX)*(S)+int(cY/gridY)
        print tarGrid

        # Asssign True Value
        class_prob[tarGrid, classid] = 1.0
        confidence[tarGrid,:] = 1.0
        offsetX   [tarGrid,:] = (cX/float(gridX)) - int(cX/gridX)
        offsetY   [tarGrid,:] = (cY/float(gridY)) - int(cY/gridY)
        norsqrtW  [tarGrid,:] = np.sqrt(boxW/W)
        norsqrtH  [tarGrid,:] = np.sqrt(boxH/H)
        
        # Flatten  
        class_prob = class_prob.flatten()
        confidence = confidence.flatten()
        #######
        tmp = np.dstack([offsetX,offsetY,norsqrtW,norsqrtH])
        print tmp
        tmp=tmp.flatten()
        print tmp

        return np.concatenate([class_prob, confidence, tmp])

In [31]:
for cX,cY in [(225,225)]:
        encode(3, cX, cY, 112, 12)
        

4
[[[ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 0.51006711  0.51006711  0.5         0.16366342]
  [ 0.51006711  0.51006711  0.5         0.16366342]]

 [[ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]]
[ 0.          0.          0.          0.    